//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcNorthwind.Models.Northwind
{
    using System;
    using System.Collections.Generic;
    //I added it
    using System.ComponentModel.DataAnnotations;
    
    public partial class Category
    {
        public int CategoryID { get; set; }
       // [Display(Name = "CATEGORY"), Required]

        public string CategoryName { get; set; }
    //    [Required]
        //AJAX
       // [StringLength(30, ErrorMessage = "The {0} must be between {2} and {1} characters.", MinimumLength = 5)]

        public string Description { get; set; }
        public byte[] Picture { get; set; }
    }
}
